### ISSUE TITLE
Trouble installing bioread

### ISSUE THREAD

**Issue by 2puppies** [njvack/bioread#12]
Hello,

I am a new Python user attempting to use bioread to convert files from aqknowledge to matlab. I am using a 64-bit PC, and I have downloaded Matlab, Python, numpy, scipy and bioread. Can someone walk me through the installation process for this package? I can't seem to get it to work.

Thank you so much for your help!!

**Comment by njvack** [comment]
Are you using Windows or Linux or OS X?

If you're on a unix-y thing, you can probably (hopefully!) do:

`pip install bioread`

or maybe

`sudo pip install bioread`

and it should get installed.

I don't know so much about installing python packages in Windows, alas.

**Comment by 2puppies** [comment]
Thanks, I figured out how to install! However, now I am having trouble implementing bioread. How do I go about running bioread to convert a folder of data using the Command prompt window (on a 64-bit windows computer, using python 2.7)?

**Comment by njvack** [comment]
Answered in #13
