### ISSUE TITLE
Could reading in of markers be added?

### ISSUE THREAD

**Issue by gchadder3** [njvack/bioread#2]
Hi,

I'm using bioread to read in experimental data collected from Biopac for stress classification.  Your package works great for reading in the channel data itself, but the one thing that seems to be missing is reading in of the markers.  (I looked in readers.py, but didn't see code to pull these out.)  

We use the markers to record when trial phases of our experiments begin and currently to extract that information from the acq file, we have to put it into a journal using the Biopac software, and then copy the journal text into a Notepad file as a first step for our data munging.  So, it would be useful if we could pull out the markers times and labels directly from the acq files to avoid this manual step.

Regards,

George Chadderdon
Design Interactive, Inc.

**Comment by dgfitch** [comment]
I think @njvack's suspicion is correct that bioread is not quite getting the end of the file parsed right. Which makes this harder/impossible. 

Once #3 is fixed with some tests behind it, this might get simpler.

My fork (coming soon to a pull request near you) adds related tests, including a test file with a marker.

**Comment by dgfitch** [comment]
It looks like the newer formats definitely have non-documented additions to the marker structure.

The marker header looks like this in 4.2.0:

    long (4): marker header total length
    long (4): marker count

Each marker in 4.2.0 is:

    long (4): marker location in samples, may start at 1 instead of 0
    short (2): ??? does not look like length of the rest of the marker
    bool (2) * 4: ???
    short (2): ??? some kind of enum
    string (4): NON-null terminated string representing type of marker, like "apnd" for segments, "flag" for the default markers, "defl" for default (?)
    long (4): marker name length
    string: marker name, null-terminated
    long (4): usually zero?? could be 2 bools


Going to need more samples to suss out the version 3 header, it's simpler but doesn't match up to the notes. Pretty sure the header is

    short (2): marker header total length
    long (4): marker count

(I really don't understand why the marker count would ever need to be bigger than the total length, but okay.)

And each marker is something like

    long (4): marker location, looks like it starts at 0 and is reversed endian from the v4???
    something: possibly of variable length :(
    long (4): marker name length
    ??? (2): unknown
    string: marker name, null-terminated

**Comment by njvack** [comment]
OK! Despite the fact that we're not reading to the end of the data quite correctly, there's enough information in the headers to go right out there and find the markers. So this is now a thing.

The thing I haven't added is slicing channels based on markers; however, you can get the sample number with marker.sample_index. This is in the file's *base* sampling rate -- so the numbers may be unexpected if you're looking at a channel with  a frequency divider. Doing it better would be a bit complicated and kind of warrants a refactoring of a bunch of stuff I'm not going to refactor right now.

Anyhow! This is closed by 0e6e573b099bc6ded8325b8325bff438f3221ca7.
