### ISSUE TITLE
function to write to matlab files doesn't work 

### ISSUE THREAD

**Issue by bobchicken** [njvack/bioread#20]
MatlabWriter.write_file(data, "emg.mat") 

  File "<ipython-input-30-70f2868aed87>", line 1, in <module>
    MatlabWriter.write_file(data, "emg.mat")

NameError: name 'MatlabWriter' is not defined

matlabwriter.write_file(data, 'emg.mat')
Traceback (most recent call last):

  File "<ipython-input-33-78ec38964383>", line 1, in <module>
    matlabwriter.write_file(data, 'emg.mat')

**AttributeError: module 'bioread.writers.matlabwriter' has no attribute 'write_file'**

**Comment by njvack** [comment]
```python
from bioread.writers import matlabwriter
matlabwriter.MatlabWriter.write_file(data, 'emg.mat')
```
works for me. You could also do:
```python
from bioread.writers.matlabwriter import MatlabWriter
MatlabWriter.write_file(data, 'emg.mat')
```
... they're functionally identical. Note that you'll need scipy installed for it to work, bioread uses their `savemat()` function.
